robot_caps:
  topics:
    - name: "/cmd_vel"
      type: "geometry_msgs/msg/Twist"
      plugin_name: "SetCmd_vel"
      description: "Set robot linear and angular velocities."
  builtins:
    - name: "Wait"
      description: "Wait for a specified duration in seconds."
      params:
        duration: float
