robot_caps:
  topics:
    - name: "/cmd_vel"
      friendly_name: "Drive base velocity"
      type: "geometry_msgs/msg/Twist"
      qos: "1"
      description: "Control robot movement"
    - name: "/battery_state"
      friendly_name: "Battery level"
      type: "sensor_msgs/msg/BatteryState"
      qos: "1"
      description: "Report battery status"
  actions:
    - name: "/navigate_to_pose"
      friendly_name: "Navigate to Pose"
      type: "nav2_msgs/action/NavigateToPose"
      description: "Drive to a specific position"
    - name: "/dock"
      friendly_name: "Dock"
      type: "irobot_create_msgs/action/Dock"
      description: "Drive to and dock with the charging station"
    - name: "/undock"
      friendly_name: "Undock"
      type: "irobot_create_msgs/action/Undock"
      description: "Leave the charging station and become ready to drive"
  services:
    - name: "/reset_odometry"
      friendly_name: "Reset Odometry"
      type: "std_srvs/srv/Empty"
      description: "Reset the robot's odometry"
    - name: "/start_motor"
      friendly_name: "Start Motor"
      type: "std_srvs/srv/Empty"
      description: "Enable the robot's motors"
    - name: "/stop_motor"
      friendly_name: "Stop Motor"
      type: "std_srvs/srv/Empty"
      description: "Disable the robot's motors"
